/**********************************************************************************************************************
 * \file HAL_write_init_values_function.c
 * \copyright Copyright (C) THD & Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
  *********************************************************************************************************************/
/*
 * HAL_write_init_values_function.c
 *
 *  Created on: 26.02.2025
 *      Author: Harry
 */


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
/*
 * IfxPort.h includes the definitions of the Infineon iLLDs for access to ports, peripherals, etc.
 */

#include "HAL_Init_Struct.h"
#include "HAL_Return_Types.h"


/* test area */


/*********************************************************************************************************************/
/*-----------------------------------------------------Functions-----------------------------------------------------*/
/*********************************************************************************************************************/
/*
 * function:    Func_HAL_write_init_values()
 * returns:     uint8: Error report
 * parameters:  pointer to Register32_Init_Entry
 *              length of array pointed to by 1st parameter
 * description: The function initializes Port 14 Pin 1 of TC375
 */
HAL_Return_Type Func_HAL_write_init_values(Register32_Init_Entry init_table[], int table_length)
{
    uint32 tmp1;
    int i;

    for (i = 0; i < table_length; i++)
    {
        tmp1 = *(init_table[i].Address);

        /* test area */


        tmp1 = tmp1 | init_table[i].Mask_SetBit;
        tmp1 = tmp1 & init_table[i].Mask_ClearBit;

        /* test area */


        *(init_table[i].Address) = tmp1;
    }

    return HAL_E_OK;
}




