/**********************************************************************************************************************
 * \file HAL_Init_Struct.h
 * \copyright Copyright (C) THD & Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
  *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Private Statement---------------------------------------------*/
/*********************************************************************************************************************/
/*
 * HAL_Init_Struct.h
 *
 *  Created on: 28.01.2025
 *      Author: Harry
 */


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>

#ifndef HAL_INIT_STRUCT_H_
#define HAL_INIT_STRUCT_H_


/*********************************************************************************************************************/
/*
 *  struct for initialization of a peripheral module.
 *  members of the struct
 *  uint32 *Address: address of the 32 bit register which shall be initialized.
 *  uint32 Mask_SetBit: a set bit in the mask forces the bit in the same position, *Adress is pointing to, to be set.
 *  uint32 Mask_ClearBit: a reset bit in the mask forces the bit in the same position, *Address is pointing to, to be reset.
 *
 */

typedef struct _Register32_Init_Entry
{
        uint32  *Address;
        uint32  Mask_SetBit;
        uint32  Mask_ClearBit;
} Register32_Init_Entry;



#endif /* HAL_INIT_STRUCT_H_ */
