/**********************************************************************************************************************
 * \file TC375_Port_10_functions.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The code in this file shall provide the following functionalities:
 *
 * 1) initialize TC375 Port 10 Pin 2 (P10.2) for operation of LED1 on the THD AdapterLite
 * 2) set P10.2
 * 3) clear P10.2
 *
 * Note: You can use the predefined port addresses in the include file IfxPort_reg.h
 */

/*
 * status: V01.1 2025-09-07
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * IfxPort_reg.h includes the definitions of the Infineon iLLDs for access to ports, peripherals, etc.
 */

#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>

#include <Level_04_HAL/TC375_SCU/TC375_SCU_WDT_functions.h>
#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPort_reg.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*
 * function:    Func_Port_10_Pin_2_init
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function initializes Port 10 Pin 2 (P10.2) of TC375 for operation of LED1
 */
HAL_Return_Type Func_Port_10_Pin_2_init (void)
{
    HAL_Return_Type tmp;

    /*
     * set P10.2 output to 1 -> switch off LED1
     */
    P10_OMR.B.PCL2 = 0x1;

    /*
     * set P10.2 in IOCR0 register to push/pull general purpose output
     */
    P10_IOCR0.B.PC2 = 0x10;

    if (P10_IOCR0.B.PC2 != 0x10)
    {
        tmp = HAL_E_NOT_OK;
    }
    else
    {
        Func_clear_Global_ENDINIT();

        /*
         * set P10.2 to strong driver / medium edge
         */
        P10_PDR0.B.PD2 = 0x1;

        Func_set_Global_ENDINIT();

        if (P10_PDR0.B.PD2 != 0x1)
        {
            tmp = HAL_E_NOT_OK;
        }
        else
        {
            tmp = HAL_E_OK;
        }
    }

    return tmp;
}


/*********************************************************************************************************************/
/*
 * function:    Func_set_Port_10_Pin_2
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function switches on pin 2 on port 10 of TC375
 */
HAL_Return_Type Func_set_Port_10_Pin_2 (void)
{
    /*
     * set P10.2 output to 1 -> switch off LED1
     */
    P10_OMR.B.PS2 = 1;

    return HAL_E_OK;
}


/*********************************************************************************************************************/
/*
 * function:    Func_clear_Port_10_Pin_2
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function switches off pin 2 on port 10 of TC375
 */
HAL_Return_Type Func_clear_Port_10_Pin_2 (void)
{
    /*
     * set P10.2 output to 0 -> switch on LED1
     */
    P10_OMR.B.PCL2 = 0x1;

    return HAL_E_OK;
}

HAL_Return_Type Func_Port_10_Pin_7_init (void)
{
    HAL_Return_Type tmp;
    P10_IOCR4.B.PC7 = 0x0;
    if (P10_IOCR4.B.PC7 != 0x0)
    {
        tmp = HAL_E_NOT_OK;
    }
    else
    {
        tmp = HAL_E_OK;
    }
    return tmp;
}

HAL_Return_Type Func_read_Port_10_Pin_7 (uint32* status)
{
    *status = P10_IN.U;
    return HAL_E_OK;
}
