/**********************************************************************************************************************
 * \file TC375_Port_02_functions.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The code in this file shall provide the following functionalities:
 *
 * 1) initialize TC375 Port 02 Pin 0 (P02.00) for operation ASCLIN2 Transmit Data Out
 * 2) initialize TC375 Port 02 Pin 3 (P02.03) for operation ASCLIN2 Slave Select Out
 * 3) initialize TC375 Port 02 Pin 4 (P02.04) for operation ASCLIN2 Clock Out
 *
 * Note: You can use the predefined port addresses in the include file IfxPort_reg.h
 */

/*
 * status: V01.0 2025-09-13
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * IfxPort_reg.h includes the definitions of the Infineon iLLDs for access to ports, peripherals, etc.
 */

#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>

#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>

#include <Level_04_HAL/TC375_SCU/TC375_SCU_WDT_functions.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPort_reg.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*
 * function:    Func_Port_02_Pin_3_init
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function initializes P02.03 for ASCLIN2 Slave Select Out (ASLSO)
 */
HAL_Return_Type Func_Port_02_Pin_3_init (void)
{
    HAL_Return_Type tmp = HAL_E_NOT_OK;

    /*
     * set P02.03 in IOCR0 register to push/pull output option 2
     */
    P02_IOCR0.B.PC3 = 0x12;

    if (P02_IOCR0.B.PC3 != 0x12)
    {
        tmp = HAL_E_NOT_OK;
    }
    else
    {
        Func_clear_Global_ENDINIT();

        /*
         * set P02.03 to strong driver / medium edge
         */
        P02_PDR0.B.PD3 = 0x1;

        Func_set_Global_ENDINIT();

        if (P02_PDR0.B.PD3 != 0x1)
        {
            tmp = HAL_E_NOT_OK;
        }
        else
        {
            tmp = HAL_E_OK;
        }
    }

    return tmp;
}


/*********************************************************************************************************************/
/*
 * function:    Func_Port_02_Pin_0_init
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function initializes P02.03 for ASCLIN2 Transmit Data Out (ATX)
 */
HAL_Return_Type Func_Port_02_Pin_0_init (void)
{
    HAL_Return_Type tmp = HAL_E_NOT_OK;

    /*
     * set P02.00 in IOCR0 register to push/pull output option 2
     */
    P02_IOCR0.B.PC0 = 0x12;

    if (P02_IOCR0.B.PC0 != 0x12)
    {
        tmp = HAL_E_NOT_OK;
    }
    else
    {
        Func_clear_Global_ENDINIT();

        /*
         * set P02.00 to strong driver / medium edge
         */
        P02_PDR0.B.PD0 = 0x1;

        Func_set_Global_ENDINIT();

        if (P02_PDR0.B.PD0 != 0x1)
        {
            tmp = HAL_E_NOT_OK;
        }
        else
        {
            tmp = HAL_E_OK;
        }
    }

    return tmp;
}


/*********************************************************************************************************************/
/*
 * function:    Func_Port_02_Pin_4_init
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function initializes P02.04 for ASCLIN2 Clock Out (ASCLK)
 */
HAL_Return_Type Func_Port_02_Pin_4_init (void)
{
    HAL_Return_Type tmp = HAL_E_NOT_OK;

    /*
     * set P02.04 in IOCR0 register to push/pull output option 2
     */
    P02_IOCR4.B.PC4 = 0x12;

    if (P02_IOCR4.B.PC4 != 0x12)
    {
        tmp = HAL_E_NOT_OK;
    }
    else
    {
        Func_clear_Global_ENDINIT();

        /*
         * set P02.03 to strong driver / medium edge
         */
        P02_PDR0.B.PD4 = 0x1;

        Func_set_Global_ENDINIT();

        if (P02_PDR0.B.PD4 != 0x1)
        {
            tmp = HAL_E_NOT_OK;
        }
        else
        {
            tmp = HAL_E_OK;
        }
    }

    return tmp;
}

HAL_Return_Type Func_Port_02_Pin_1_init (void)
{
    HAL_Return_Type tmp;
    P02_IOCR0.B.PC1 = 0x0;
    if (P02_IOCR0.B.PC1 != 0x0)
    {
        tmp = HAL_E_NOT_OK;
    }
    else
    {
        tmp = HAL_E_OK;
    }
    return tmp;
}

HAL_Return_Type Func_read_Port_02_Pin_1 (uint32* status)
{
    *status = P02_IN.U;
    return HAL_E_OK;
}

