/**********************************************************************************************************************
 * \file TC375_CCUCON_functions.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The code in this file shall provide the following functionalities:
 *
 * 1) set clock input to MCAN module (MCANH) to 100 Mhz
 * 2) set clock input to CAN Baud rate generation (MCAN) to 80 Mhz
 *
 * Note: You can use the predefined port addresses in the include file IfxPort_reg.h
 */

/*
 * status: V01.1 2025-12-13
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * IfxPort_reg.h includes the definitions of the Infineon iLLDs for access to ports, peripherals, etc.
 */

#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>

#include <Level_04_HAL/TC375_SCU/TC375_SCU_WDT_functions.h>
#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxScu_reg.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*
 * function:    Func_MCANH_clock_set
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function sets the clock for MCANH (MCAN module) to 100 Mhz
 */
HAL_Return_Type Func_MCANH_clock_set(void)
{
    HAL_Return_Type tmp_HAL = HAL_E_OK;

    Func_clear_Global_SafeENDINIT();

    /*
     * set MCANH clock to fPLL0 / 3 => 300 Mhz / 3 = 100 Mhz
     */
    SCU_CCUCON5.B.MCANHDIV = 0x3;

    Func_clear_Global_SafeENDINIT();

    if (SCU_CCUCON5.B.MCANHDIV == 0x3)
    {
        tmp_HAL = HAL_E_OK;
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }

    return tmp_HAL;
}


/*********************************************************************************************************************/
/*
 * function:    Func_MCAN_Baudrate_clock_set
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function sets the clock for MCAN Baud rate generation to 80 Mhz
 */
HAL_Return_Type Func_MCAN_Baudrate_clock_set(void)
{
    HAL_Return_Type tmp_HAL = HAL_E_OK;

    Func_clear_Global_SafeENDINIT();

    /*
     * set MCANH clock to fPLL1 / 2 => 160 Mhz / 2 = 80 Mhz
     */
    SCU_CCUCON1.B.CLKSELMCAN = 0x2;
    SCU_CCUCON1.B.MCANDIV    = 0x1;

    Func_clear_Global_SafeENDINIT();

    if ((SCU_CCUCON1.B.CLKSELMCAN == 0x2) && (SCU_CCUCON1.B.MCANDIV == 0x1))
    {
        tmp_HAL = HAL_E_OK;
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }

    return tmp_HAL;
}






