/**********************************************************************************************************************
 * \file TC375_IR_functions.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The code in this file shall provide the following functionalities:
 *
 * Job description:
 *
 * Initialization of the Service Request Nodes (SRN) for the interrupts generated by the GPT12 timer
 *
 *
 *
 * Note: You can use the predefined port addresses in the include file IfxPort_reg.h
 */

/*
 * status: V01.0 2025-09-16
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Platform_Types.h"
#include "IfxSrc_reg.h"

#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>
#include <Level_02_Interfaces/TC375_IntVectorTable_CPU0/IntVectorTable_CPU0.h>
#include <Level_04_HAL/TC375_GPT12/TC375_GPT12_functions.h>
#include <Level_04_HAL/TC375_DMA/TC375_DMA_functions.h>
#include <Level_Libraries/Infra/Platform/Tricore/Compilers/Compilers.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/

extern volatile boolean g_send_due;

/*********************************************************************************************************************/
/*-----------------------------------------------------Functions-----------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*
 * function:    Func_TC375_IR_SRN_GPT120T6_init
 * returns:     HAL_Return_Type Error report
 * parameters:  void
 * description: The function initializes the interrupt node SRN GPT120T6. The interrupt is triggered by GPT12 Timer6.
 */

HAL_Return_Type Func_TC375_IR_SRN_GPT120T6_init(void)
{
    HAL_Return_Type tmp;

    /*
     * the Service Request Node (SRN) im Interrupt Router is initialized
     *
     * field 7..0:   SRPN:   Service Priority Number, GPT12 T6 ISR on CPU0
     * field 10:     SRE:    0x0, service request is disabled (will be enabled separately)
     * field 13..11: TOS:    0x0, CPU0 will receive the request
     * field 25:     CLRR:   0x1, bit is set to 1 to clear service request
     * field 26:     SETR:   0x0, bit is cleared, no set request
     * field 28:     IOVCLR: 0x1, clear bit IOV
     * field 30:     SWSCLR: 0x1, clear bit sticky
     *
     */

    SRC_GPT120T6.B.SRPN   = GPT12_T6_SRPN_CPU;
    SRC_GPT120T6.B.SRE    = 0x0;
    SRC_GPT120T6.B.TOS    = TOS_CPU0;
    SRC_GPT120T6.B.CLRR   = 0x1;
    SRC_GPT120T6.B.SETR   = 0x0;
    SRC_GPT120T6.B.IOVCLR = 0x1;
    SRC_GPT120T6.B.SWSCLR = 0x1;

    /*
     * SRC_GPT120 is not checked for correct setup
     */

    tmp = HAL_E_OK;

    return tmp;
}




/*********************************************************************************************************************/
/*
 * function:    Func_TC375_IR_SRN_GPT120T6_enable
 * returns:     HAL_Return_Type Error report
 * parameters:  void
 * description: The function enables the interrupt of node SRN GPT120T6.
 */

HAL_Return_Type Func_TC375_IR_SRN_GPT120T6_enable(void)
{
    HAL_Return_Type tmp = HAL_E_NOT_OK;

    SRC_GPT120T6.B.SRE = 0x1;

    if(SRC_GPT120T6.B.SRE == 0x1)
    {
        tmp = HAL_E_OK;
    }
    else
    {
        tmp = HAL_E_NOT_OK;
    }

    return tmp;
}


/*********************************************************************************************************************/
/*
 * function:    Func_TC375_IR_SRN_GPT120T6_clear
 * returns:     HAL_Return_Type Error report
 * parameters:  void
 * description: The function clears the interrupt request of node SRN GPT120T6.
 */

HAL_Return_Type Func_TC375_IR_SRN_GPT120T6_clear(void)
{
    HAL_Return_Type tmp = HAL_E_NOT_OK;

    SRC_GPT120T6.B.CLRR = 0x1;

    if(SRC_GPT120T6.B.SRR == 0x0)
    {
        tmp = HAL_E_OK;
    }
    else
    {
        tmp = HAL_E_NOT_OK;
    }

    return tmp;
}



/* no CPU ISR when T6 routes to DMA */


