/**
 * \File Ifx_reg.h
 * \brief
 * Version: TC37xPD_UM_V1.5.0
 * Specification: TC3xx User Manual V1.5.0
 * MAY BE CHANGED BY USER [yes/no]: No
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */


#ifndef IFX_REG_H
#define IFX_REG_H 1

#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxAsclin_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxCan_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxCbs_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxCcu6_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxConverter_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxCpu_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxDma_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxDmu_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxDom_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxEdsadc_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxEray_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxEvadc_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxFce_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxFsi_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxGeth_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxGpt12_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxHsct_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxHssl_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxI2c_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxInt_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxIom_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxMinimcds_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxMsc_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxMtu_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPfi_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPms_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPmu_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPort_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPsi5_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPsi5s_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxQspi_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxSbcu_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxScu_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxSent_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxSmu_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxSrc_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxStm_reg.h>

#include "IfxGtm_reg.h"

#endif /*IFX_REG_H*/
