/**********************************************************************************************************************
 * \file Task_Objects.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Harald
 *Zweck. If and as long as no such terms of use are agreed, use of this file is
 *subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 *  In this file all tasks and their handles are defined.
 *  Afterwards the FreeRTOS scheduler is started.
 *
 */

/*
 * status: V01.0 2025-09-15
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include <Level_03_OS/FreeRTOS/include/FreeRTOS.h>
#include <Level_03_OS/FreeRTOS/include/task.h>

#include <Level_02_Interfaces/AdapterLite/IF_Display.h>
#include <Level_02_Interfaces/Interface_Libraries/L02_Return_Types.h>
#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>
#include <Level_04_HAL/TC375_GPT12/TC375_GPT12_functions.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPort_reg.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/

extern void task_Switches(void *arg);
extern void task_Display(void *arg);

/*********************************************************************************************************************/
/*-------------------------------------------------Global
 * variables--------------------------------------------------*/
/*********************************************************************************************************************/

TaskHandle_t handle_task_Switches;
TaskHandle_t handle_task_Display;

/*********************************************************************************************************************/
/*---------------------------------------------Function
 * Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void Tasks_Init(void) {
  /*
   * Create task(s)
   *
   * parameter 1: task_HeartBeat_LED1; the function which will be handled as a
   * task parameter 2: "Digital Control LED1"; just a name for the task, will
   * not be used in the further codes parameter 3: configMINIMAL_STACK_SIZE; a
   * parameter to configure the task parameter 4: NULL; a parameter to configure
   * the task parameter 5: 0; a parameter to configure the task parameter 6:
   * &handle_HeartBeat_LED1; will be used as reference to the task
   */

  /*
   * Create task(s)
   *
   * parameter 1: task_Display; the function which will be handled as a task
   * parameter 2: "task Display"; just a name for the task, will not be used in
   * the further codes parameter 3: configMINIMAL_STACK_SIZE; a parameter to
   * configure the task parameter 4: NULL; a parameter to configure the task
   * parameter 5: 0; a parameter to configure the task
   * parameter 6: &handle_task_Display; will be used as reference to the task
   */

  xTaskCreate(task_Display, "task Display", configMINIMAL_STACK_SIZE, NULL, 1,
              &handle_task_Display);

  /*
   * The tasks are defined. Now the scheduler of FreeRTOS can be started.
   * The scheduler will start all tasks.
   * Start the scheduler.
   */
  /* Force-start GPT12 T6 for test (ignore switches) */
  extern volatile uint8 g_send_divider;
  extern volatile uint8 g_send_tick;

  g_send_divider = 1u; /* force 1s mode */
  g_send_tick = 0u;

  Func_GPT12_T6_init();
  Func_GPT12_T6_set_period_1s();
  Func_GPT12_T6_enable_interrupts();
  /* Configure LED1 pin P10.2 as push-pull output for direct toggling */
  MODULE_P10.IOCR0.B.PC2 = 0x10; /* push-pull output */
  Func_GPT12_T6_start();

  /* Initialize LED1 adapter functions */
  extern L02_Return_Type Func_Adapter_LED1_init(void);
  Func_Adapter_LED1_init();

  vTaskStartScheduler();
}
