/**********************************************************************************************************************
 * \file TC375_ASCLIN2_functions.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The code in this file shall provide the following functionalities:
 *
 * 1) initialize the ASCLIN2 serial interface as SPI interface
 *
 * Note: You can use the predefined port addresses in the include file IfxPort_reg.h
 */

/*
 * status: V01.0 2025-09-14
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * IfxPort_reg.h includes the definitions of the Infineon iLLDs for access to ports, peripherals, etc.
 */

#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>

#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>

#include <Level_04_HAL/TC375_SCU/TC375_SCU_WDT_functions.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxAsclin_reg.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

uint16 tmp_data;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*
 * function:    Func_ASCLIN2_init
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function initializes the ASCLIN2 module for operation as
 *              SPI with Transmit Data (ATX), Transmit Serial Clock (ASCLK), Slave Select Out (ASLSO)
 *              data frame length is 16 bit
 *              MSB is shifted first
 */
HAL_Return_Type Func_ASCLIN2_init (void)
{
    HAL_Return_Type tmp_HAL = HAL_E_NOT_OK;
    uint32 tmp_int32;

    Func_clear_Global_ENDINIT();

    /*
     * enable the ASCLIN2 module and switch on the module clock
     * DISR = 0 -> clear disable request
     * EDIS = 1 -> disable sleep mode
     */

    ASCLIN2_CLC.B.DISR = 0x0;
    ASCLIN2_CLC.B.EDIS = 0x1;

    if(ASCLIN2_CLC.B.DISR == 0x0)
    {
        if(ASCLIN2_CLC.B.EDIS == 0x1)
        {
            tmp_HAL = HAL_E_OK;
        }
        else
        {
            tmp_HAL = HAL_E_NOT_OK;
        }
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }

    /*
     * do dummy read to finish register setup
     */

    tmp_int32 = ASCLIN2_CLC.U;

    Func_set_Global_ENDINIT();

    /*
     * next init sequence
     */

    if(tmp_HAL == HAL_E_OK)
    {
        /*
         * for initialization the clock must be switched off. See manual ASCLIN.
         * the following registers can only be written when CLKSEL = 0:
         * IOCR, BITCON, FRAMECON, BRG, BRD, LINCON, LINBTIMER, LINHTIMER
         */

        ASCLIN2_CSR.B.CLKSEL = 0x0;

        /*
         * for the receive signal ASCLIN2_ARX the pin ASCLIN2_ARXB / pin P02.1 is selected.
         * for the interface to the display module the receive function will not be used.
         *
         * the glitch filter depth is set to 50% size.
         * the CTS input is disabled.
         * the CTS input is set to ACTSB, which is Port 33.5. The signal is not used.
         * the RTS CTS Polarity is set to 0. Both signals are not used.
         * the polarity of the clock signal in idle mode is set to 1.
         * the polarity of the Slave Select Signal in idle mode is set to 1. We need a rising edge at the end
         *     of data transmission to latch the data.
         * the Loop-back mode and the CTS input are not used.
         */

        ASCLIN2_IOCR.B.ALTI  = 0x1;
        ASCLIN2_IOCR.B.DEPTH = 0x1F;
        ASCLIN2_IOCR.B.CTSEN = 0x0;
        ASCLIN2_IOCR.B.CTS   = 0x1;
        ASCLIN2_IOCR.B.RCPOL = 0x1;
        ASCLIN2_IOCR.B.CPOL  = 0x1;
        ASCLIN2_IOCR.B.SPOL  = 0x1;
        ASCLIN2_IOCR.B.LB    = 0x0;

        /*
         * ASCLIN2_IOCR is not checked for correct setup
         */


        /*
         * the register Bitcon is part 1 of the Baud Rate definition
         *
         * the source frequency is fASCLINSI = 80Mhz.
         * target frequency is 5Mbaud
         *
         * Prescaler is set to 4, Oversampling is set to 3
         * Sample Point Position and Sample Point are don't care, no data is received
         */

        ASCLIN2_BITCON.B.PRESCALER    = 3;     // 5 MBaud
        ASCLIN2_BITCON.B.OVERSAMPLING = 0x3;
        ASCLIN2_BITCON.B.SAMPLEPOINT  = 0x1;

        /*
         * ASCLIN2_BITCON is not checked for correct setup
         */


        /*
         * the register BRG is part 2 of the Baud Rate definition
         *
         * the NUMERATOR is set to 1
         * the DENOMINATOR is set to 1
         */

        ASCLIN2_BRG.B.NUMERATOR   = 1;
        ASCLIN2_BRG.B.DENOMINATOR = 1;



        /*
         * the register DATCON defines the length of a frame in bits
         *
         * the of the SPI frame is set to 16 decimal
         */

        ASCLIN2_DATCON.B.DATLEN = 0xF;

        /*
         * ASCLIN2_DATCON is not checked for correct setup
         */


        /*
         * the register FRAMECON defines the format of the transmitted frames
         * the MODE field is set to SPI mode
         * the IDLE field is set to 2 bits -> at least 2 bits are inserted between SPI frames
         * the STOP field is set to 1 bit -> 1 bit is appended at the end of the frame
         * the LEAD field is set to 1 bit -> 1 bit is inserted at the beginning of the frame
         * the MSB field is set to 1 -> MSB is shifted out first
         * collision detection and parity are not used and disabled
         */

        ASCLIN2_FRAMECON.B.MODE = 0x2;
        ASCLIN2_FRAMECON.B.IDLE = 0x2;
        ASCLIN2_FRAMECON.B.STOP = 0x1;
        ASCLIN2_FRAMECON.B.LEAD = 0x1;
        ASCLIN2_FRAMECON.B.MSB  = 0x1;
        ASCLIN2_FRAMECON.B.PEN  = 0x0;
        ASCLIN2_FRAMECON.B.CEN  = 0x0;

        /*
         * ASCLIN2_FRAMECON is not checked for correct setup
         */


        /*
         * the transmit FIFO function is not used
         * but it has to be initialized correctly
         */

        ASCLIN2_TXFIFOCON.B.FLUSH    = 0x1;         // FIFO is flushed
        ASCLIN2_TXFIFOCON.B.ENO      = 0x1;         // FIFO send output is enabled
        ASCLIN2_TXFIFOCON.B.FM       = 0x0;         // FIFO fill mode is set to combined mode
        ASCLIN2_TXFIFOCON.B.INW      = 0x2;         // the FIFO will be filled with 16 bit (2 byte) writes
        ASCLIN2_TXFIFOCON.B.INTLEVEL = 0x0;         // the FIFO triggers an interrupt as soon as the last value is shifted out
                                                    // (not used)
        /*
         * ASCLIN2_TXFIFOCON is not checked for correct setup
         */

        /*
         * the receive FIFOs is not used, the ASCLIN module only sends data
         * the receive FIFO is disabled
         */

        ASCLIN2_RXFIFOCON.U    = 0x0;         // FIFO is disabled


        /*
         * the clock for Baud Rate generation has to be re-enabled
         * the clock source is set to fASCLINS (80Mhz)
         */

        ASCLIN2_CSR.B.CLKSEL = 0x4;

        /*
         * ASCLIN2_CSR is not checked for correct setup
         */


        /*
         * the flags are all disabled and cleared
         */

        ASCLIN2_FLAGSENABLE.U = 0x0;
        ASCLIN2_FLAGSCLEAR.U  = 0x0;

        /*
         * ASCLIN2_FLAGS are not checked for correct setup
         */

    }

    return tmp_HAL;
}


