/**********************************************************************************************************************
 * \file IntVectorTable_Cpu0.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Harald
 *Zweck. If and as long as no such terms of use are agreed, use of this file is
 *subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * This file holds the indexes into the Interrupt Vector Table of Cpu0.
 *
 * Job description
 *
 * Define the indexes of the ISR addresses in the IVT0
 *
 */

/*
 * status: V01.1 2025-09-16
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/

#ifndef INTVECTORTABLE_CPU0_H_
#define INTVECTORTABLE_CPU0_H_

/* Interrupt Service Request Priority Numbers (SRPN's)  */

#define GPT12_T6_SRPN_CPU (0x30)
#define GPT12_T3_SRPN_CPU (0x31) /* GPT12 T3 routed to CPU (added) */
#define T6_SRPN_to_DMA_Ch0 (0x0)
#define T6_SRPN_to_DMA_Ch1 (0x1)
#define T3_SRPN_to_DMA_Ch8 (0x8)
#define DMA_CH1_to_ISR_x12 (0x12)
#define DMA_CH8_to_ISR_x11 (0x11)

/* Interrupt Type of Services (TOS)     */

#define SCU_ERU_OGU0_TOS_CPU0 0x0
#define SCU_ERU_OGU3_TOS_CPU0 0x0

#define TOS_CPU0 0x0

#define TOS_DMA 0x1

void Func_Init_IVT(void);

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#endif /* INTVECTORTABLE_CPU0_H_ */
