/**********************************************************************************************************************
 * \file TC375_GPT12_PISEL_functions.c
 * \copyright Copyright (C) THD & Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
  *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
/*
 * IfxPort.h includes the definitions of the Infineon iLLDs for access to ports, peripherals, etc.
 */

#include <Level_04_HAL/HAL_Libraries/HAL_Init_Struct.h>
#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>

#include <Level_04_HAL/TC375_SCU/TC375_SCU_WDT_functions.h>
#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxGpt12_reg.h>


/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*-----------------------------------------------------Functions-----------------------------------------------------*/
/*********************************************************************************************************************/
/*
 * function:    Func_GPT12_PISEL_init
 * returns:     HAL_Return_Type Error report
 * parameters:  void
 * description: The function initializes timer GPT12 PISEL register
 *
 */
HAL_Return_Type Func_GPT12_PISEL_init (void)
{
    HAL_Return_Type tmp_HAL = HAL_E_OK;

    /*
     * the timer register PISEL is configured to define the connections to pins
     *
     field 01: IST2IN: 0x0, bit is don't care
     field 02: IST2EUD: 0x0, bit is don't care
     field 03..02: IST3IN: 0x1, T3INB selected @ port 10.4
     field 05..04: IST3EUD: 0x0, T3EUDA selected @ port 2.7
     field 07..06: IST4IN: 0x0, T4INA selected @ port 2.8
     field 09..08: IST4EUD: 0x0, bit is don't care
     field 10: IST5IN: 0x0, bit is don't care
     field 11: IST5EUD: 0x0, bit is don't care
     field 12: IST6IN: 0x0, bit is don't care
     field 13: IST6EUD: 0x0, bit is don't care
     field 15..14: ISCAPIN: 0x0, bit is don't care
     field 31..16: reserved

     pin mappings:
     Signal GPT12 T3INB  -> Port P10.4 -> SIA
     Signal GPT12 T3EUDA -> Port 2.7   -> SIB
     Signal GPT12 T4INA  -> Port 2.8   -> SW
     *
     */

    GPT120_PISEL.B.IST2IN  = 0x0;
    GPT120_PISEL.B.IST2EUD = 0x0;
    GPT120_PISEL.B.IST3IN  = 0x1;
    GPT120_PISEL.B.IST3EUD = 0x0;
    GPT120_PISEL.B.IST4IN  = 0x0;
    GPT120_PISEL.B.IST4EUD = 0x0;
    GPT120_PISEL.B.IST5IN  = 0x0;
    GPT120_PISEL.B.IST5EUD = 0x0;
    GPT120_PISEL.B.IST6IN  = 0x0;
    GPT120_PISEL.B.IST6EUD = 0x0;
    GPT120_PISEL.B.ISCAPIN = 0x0;

    return tmp_HAL;
}
