/**********************************************************************************************************************
 * \file TC375_GPT12_Module_functions.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The code in this file shall provide the following functionalities:
 *
 * 1) initialize the GPT12 timer
 * 2) start the GPT12 timer
 * 3) stop the GPT12 timer
 * 4) (re)-load the GPT12 timer values
 *
 * Note: You can use the predefined port addresses in the include file IfxPort_reg.h
 */

/*
 * status: V01.0 2025-09-17
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * IfxPort_reg.h includes the definitions of the Infineon iLLDs for access to ports, peripherals, etc.
 */

#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>
#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>
#include <Level_04_HAL/TC375_SCU/TC375_SCU_WDT_functions.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxGpt12_reg.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/



/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*
 * function:    Func_GPT12_Module_init
 * returns:     HAL_Return_Type error report
 * parameters:  void
 * description: The function initializes the GPT12 module for operation
 */

HAL_Return_Type Func_GPT12_Module_init (void)
{
    HAL_Return_Type tmp_HAL = HAL_E_NOT_OK;
    uint32 tmp_int32;

    Func_clear_Global_ENDINIT();

    /*
     * enable the GPT12 module and switch on the module clock
     * DISR = 0 -> clear disable request
     * EDIS = 1 -> disable sleep mode
     * other bits are reserved or read only
     */

    GPT120_CLC.B.DISR = 0x0;
    GPT120_CLC.B.EDIS = 0x1;

    Func_set_Global_ENDINIT();

    if(GPT120_CLC.B.DISS == 0x0)    // DISS == 0x0 -> GPT12 is successfully enabled
    {
        tmp_HAL = HAL_E_OK;
    }
    else
    {
        tmp_HAL = HAL_E_NOT_OK;
    }

    /*
     * do dummy read to finish register setup
     */
    tmp_int32 = GPT120_CLC.U;

    return tmp_HAL;
}

HAL_Return_Type Func_GPT12_T2_init(void)
{
    HAL_Return_Type tmp = Func_GPT12_Module_init();
    if (tmp != HAL_E_OK)
    {
        return tmp;
    }

    GPT120_T2CON.B.T2M = 0x0;
    GPT120_T2CON.B.T2I = 0x0;
    GPT120_T2CON.B.T2UD = 0x0;
    GPT120_T2CON.B.T2UDE = 0x0;
    GPT120_T2CON.B.T2RC = 0x0;
    GPT120_T2CON.B.T2IRDIS = 0x0;
    GPT120_T2CON.B.T2R = 0x0;
    GPT120_T2.U = 0x0;

    return HAL_E_OK;
}

HAL_Return_Type Func_GPT12_T2_set_value(uint16 timer_value)
{
    GPT120_T2.U = ((uint32)timer_value & 0x0000FFFFu);
    return HAL_E_OK;
}

HAL_Return_Type Func_GPT12_T2_start(void)
{
    GPT120_T2CON.B.T2R = 0x1;
    return (GPT120_T2CON.B.T2R == 0x1) ? HAL_E_OK : HAL_E_NOT_OK;
}

