################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SRC_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
COMPILED_SRCS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Level_01_Tasks/CPU_0 \
Level_02_Interfaces/AdapterLite \
Level_03_OS/FreeRTOS \
Level_03_OS/FreeRTOS/portable/MemMang \
Level_03_OS/FreeRTOS/portable/Tasking/TC3 \
Level_04_HAL/TC375_CPUs \
Level_04_HAL/TC375_Ports \
Level_04_HAL/TC375_SCU \
Level_Configurations \
Level_Libraries/Infra/Platform/Tricore/Compilers \
Level_Libraries/Infra/Ssw/TC37A/Tricore \
Level_Libraries/Service/CpuGeneric/If \
Level_Libraries/Service/CpuGeneric/StdIf \
Level_Libraries/Service/CpuGeneric/SysSe/Bsp \
Level_Libraries/Service/CpuGeneric/SysSe/Comm \
Level_Libraries/Service/CpuGeneric/SysSe/General \
Level_Libraries/Service/CpuGeneric/SysSe/Time \
Level_Libraries/iLLD/TC37A/Tricore/Asclin/Asc \
Level_Libraries/iLLD/TC37A/Tricore/Asclin/Lin \
Level_Libraries/iLLD/TC37A/Tricore/Asclin/Spi \
Level_Libraries/iLLD/TC37A/Tricore/Asclin/Std \
Level_Libraries/iLLD/TC37A/Tricore/Can/Can \
Level_Libraries/iLLD/TC37A/Tricore/Can/Std \
Level_Libraries/iLLD/TC37A/Tricore/Ccu6/Icu \
Level_Libraries/iLLD/TC37A/Tricore/Ccu6/PwmBc \
Level_Libraries/iLLD/TC37A/Tricore/Ccu6/PwmHl \
Level_Libraries/iLLD/TC37A/Tricore/Ccu6/Std \
Level_Libraries/iLLD/TC37A/Tricore/Ccu6/TPwm \
Level_Libraries/iLLD/TC37A/Tricore/Ccu6/Timer \
Level_Libraries/iLLD/TC37A/Tricore/Ccu6/TimerWithTrigger \
Level_Libraries/iLLD/TC37A/Tricore/Convctrl/Std \
Level_Libraries/iLLD/TC37A/Tricore/Cpu/Irq \
Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std \
Level_Libraries/iLLD/TC37A/Tricore/Cpu/Trap \
Level_Libraries/iLLD/TC37A/Tricore/Dma/Dma \
Level_Libraries/iLLD/TC37A/Tricore/Dma/Std \
Level_Libraries/iLLD/TC37A/Tricore/Edsadc/Edsadc \
Level_Libraries/iLLD/TC37A/Tricore/Edsadc/Std \
Level_Libraries/iLLD/TC37A/Tricore/Evadc/Adc \
Level_Libraries/iLLD/TC37A/Tricore/Evadc/Std \
Level_Libraries/iLLD/TC37A/Tricore/Fce/Crc \
Level_Libraries/iLLD/TC37A/Tricore/Fce/Std \
Level_Libraries/iLLD/TC37A/Tricore/Flash/Std \
Level_Libraries/iLLD/TC37A/Tricore/Geth/Eth \
Level_Libraries/iLLD/TC37A/Tricore/Geth/Std \
Level_Libraries/iLLD/TC37A/Tricore/Gpt12/IncrEnc \
Level_Libraries/iLLD/TC37A/Tricore/Gpt12/Std \
Level_Libraries/iLLD/TC37A/Tricore/I2c/I2c \
Level_Libraries/iLLD/TC37A/Tricore/I2c/Std \
Level_Libraries/iLLD/TC37A/Tricore/Iom/Driver \
Level_Libraries/iLLD/TC37A/Tricore/Iom/Iom \
Level_Libraries/iLLD/TC37A/Tricore/Iom/Std \
Level_Libraries/iLLD/TC37A/Tricore/Mtu/Std \
Level_Libraries/iLLD/TC37A/Tricore/Pms/Std \
Level_Libraries/iLLD/TC37A/Tricore/Port/Io \
Level_Libraries/iLLD/TC37A/Tricore/Port/Std \
Level_Libraries/iLLD/TC37A/Tricore/Qspi/SpiMaster \
Level_Libraries/iLLD/TC37A/Tricore/Qspi/SpiSlave \
Level_Libraries/iLLD/TC37A/Tricore/Qspi/Std \
Level_Libraries/iLLD/TC37A/Tricore/Scu/Std \
Level_Libraries/iLLD/TC37A/Tricore/Smu/Smu \
Level_Libraries/iLLD/TC37A/Tricore/Smu/Std \
Level_Libraries/iLLD/TC37A/Tricore/Src/Std \
Level_Libraries/iLLD/TC37A/Tricore/Stm/Std \
Level_Libraries/iLLD/TC37A/Tricore/Stm/Timer \
Level_Libraries/iLLD/TC37A/Tricore/_Impl \
Level_Libraries/iLLD/TC37A/Tricore/_Lib/DataHandling \
Level_Libraries/iLLD/TC37A/Tricore/_Lib/InternalMux \
Level_Libraries/iLLD/TC37A/Tricore/_PinMap \

