/**********************************************************************************************************************
 * \file IF_Display.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The functionalities in this file belong to the Service Interface Layer of the application.
 * The services build the interface to the functions to operate the 4 segment display on the THD AdapterLite.
 *
 * The display is connected to the TC375 using a SPI - like interface.
 *
 * The Interface shall provide the functions:
 * 1) Func_Adapter_Display_init
 *    The function shall initialize the display on the THD adapter.
 *
 * 2) Func_SetDisplayBuffer
 *    The function shall transfer one character into the display input buffer.
 *
 * 3) Func_Convert2Display
 *    The function shall convert the content of the input buffer to data as required by the display.
 *
 * 4) Func_EncodeDisplayInput
 *    The function shall convert characters to code as required by the display.
 *
 * 5) Func_BuildDisplayOutput
 *    The function shall store the values to be displayed in a format which is required for the serial transfer.
 *
 * 6) Func_Build_ASCLIN_FIFO_Format
 *    The function shall store the values to be displayed in a format which is required by the FIFO of ASCLIN.
 *
 *

 */

/*
 * status: V01.0 2025-09-15
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>

#include "IF_Display.h"

#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>
#include <Level_02_Interfaces/Interface_Libraries/L02_Return_Types.h>


/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * References to functions on HAL (HW Abstraction Layer).
 */

extern HAL_Return_Type Func_Port_02_Pin_0_init (void);
extern HAL_Return_Type Func_Port_02_Pin_3_init (void);
extern HAL_Return_Type Func_Port_02_Pin_4_init (void);

extern HAL_Return_Type Func_ASCLIN2_init (void);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * the field with the position code of the display elements.
 */
const uint8 DisplayElementPositionCode[] = {0xF1,0xF2,0xF4,0xF8};


/*
 * the field with characters to be displayed.
 * DisplayInput[0] is the character on the most right hand side on the display.
 */
DisplayPrompt DisplayInputBuffer[4];


/*
 * the field with characters to be transferred to the display (encoded for the display).
 * DisplayInput[0] is the character on the most right hand side.
 */
uint8 DisplayInputEncoded[4];


/*
 * the field with the data to be output to the display elements.
 */
DisplayElementStruct DisplayOutputBuffer[4];


/*
 * the field with the data to be output to the display elements, formatted for the ASCLIN FIFO.
 */
__align(4) uint16 DisplayOutputFIFO[4];  // @suppress("Syntax error")


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*
 * function:    Func_Adapter_Display_init
 * returns:     L02_Return_Type Error report
 * parameters:  void
 * description: The function initializes the interface to the display on the MF Shield board.
 */

L02_Return_Type Func_Adapter_Display_init(void)
{
    HAL_Return_Type tmp1 = HAL_E_NOT_OK;

    tmp1 = Func_Port_02_Pin_0_init();

    if (tmp1 == HAL_E_OK)
    {
        tmp1 = Func_Port_02_Pin_3_init();

        if (tmp1 == HAL_E_OK)
        {
            tmp1 = Func_Port_02_Pin_4_init();

            if (tmp1 == HAL_E_OK)
            {
                tmp1 = Func_ASCLIN2_init ();

                if (tmp1 != HAL_E_OK)
                {
                    tmp1 = HAL_E_NOT_OK;
                }
            }
            else
            {
                tmp1 = HAL_E_NOT_OK;
            }
        }
        else
        {
            tmp1 = HAL_E_NOT_OK;
        }
    }
    else
    {
        tmp1 = HAL_E_NOT_OK;
    }

    return L02_E_OK;
}


/*********************************************************************************************************************/
/*
 * function:    Func_EncodeDisplayInput
 * returns:     L02_Return_Type Error report
 * parameters:  void
 * description: The function encodes the values to be displayed to a code as it is required by the display.
 */

L02_Return_Type Func_EncodeDisplayInput(DisplayPrompt inputfield[], uint8 outputfield[])
{
    int i;

    for (i = 0; i<4; i++)
    {
        switch (inputfield[i])
        {
            case DispPrompt_0noDot:
                outputfield[i] = 0xC0;
                break;
            case DispPrompt_1noDot:
                outputfield[i] = 0xF9;
                break;
            case DispPrompt_2noDot:
                 outputfield[i] = 0xA4;
                 break;
            case DispPrompt_3noDot:
                 outputfield[i] = 0xB0;
                 break;
            case DispPrompt_4noDot:
                outputfield[i] = 0x99;
                break;
            case DispPrompt_5noDot:
                outputfield[i] = 0x92;
                break;
            case DispPrompt_6noDot:
                 outputfield[i] = 0x82;
                 break;
            case DispPrompt_7noDot:
                 outputfield[i] = 0xF8;
                 break;
            case DispPrompt_8noDot:
                 outputfield[i] = 0x80;
                 break;
            case DispPrompt_9noDot:
                 outputfield[i] = 0x90;
                 break;
            case DispPrompt_ONnoDot:
                 outputfield[i] = 0x80;
                 break;
            case DispPrompt_0withDot:
                outputfield[i] = 0x40;
                break;
            case DispPrompt_1withDot:
                outputfield[i] = 0x79;
                break;
            case DispPrompt_2withDot:
                 outputfield[i] = 0x24;
                 break;
            case DispPrompt_3withDot:
                 outputfield[i] = 0x30;
                 break;
            case DispPrompt_4withDot:
                 outputfield[i] = 0x19;
                break;
            case DispPrompt_5withDot:
                 outputfield[i] = 0x12;
                break;
            case DispPrompt_6withDot:
                 outputfield[i] = 0x02;
                 break;
            case DispPrompt_7withDot:
                 outputfield[i] = 0x78;
                 break;
            case DispPrompt_8withDot:
                 outputfield[i] = 0x00;
                 break;
            case DispPrompt_9withDot:
                 outputfield[i] = 0x10;
                 break;
            case DispPrompt_OFF:
                 outputfield[i] = 0xFF;
                 break;
            case DispPrompt_Dot:
                 outputfield[i] = 0x7F;
                 break;
            default:
                outputfield[i] = 0xFF;
        }
    }

    return L02_E_OK;
}


/*********************************************************************************************************************/
/*
 * function:    Func_BuildDisplayOutput
 * returns:     L02_Return_Type Error report
 * parameters:  void
 * description: The function stores the values to be displayed in a format which is required for the serial transfer.
 */

L02_Return_Type Func_BuildDisplayOutput(uint8 inputfield[], DisplayElementStruct outputfield[])
{
    int i;

    for (i = 0; i < 4; i++)
    {
        outputfield[i].ElementShowCode = inputfield[i];
        outputfield[i].ElementPositionCode = DisplayElementPositionCode[i];
    }

    return L02_E_OK;
}


/*********************************************************************************************************************/
/*
 * function:    Func_Build_ASCLIN_FIFO_Format
 * returns:     L02_Return_Type Error report
 * parameters:  void
 * description: The function stores the values to be displayed in a format which is required by the FIFO of ASCLIN.
 */

L02_Return_Type Func_Build_ASCLIN_FIFO_Format(DisplayElementStruct inputfield[], uint16 outputfield[])
{
    int i;

    for (i = 0; i < 4; i++)
    {
        outputfield[i] = 0x0;
        outputfield[i] = ((inputfield[i].ElementShowCode) << 8)|(inputfield[i].ElementPositionCode);
    }

    return L02_E_OK;
}


/*********************************************************************************************************************/
/*
 * function:    Func_SetDisplayBuffer(DisplayPrompt character, int position)
 * returns:     L02_Return_Type Error report
 * parameters:  DisplayPrompt character: character to be displayed
 *              int position: position of character, allowed range 0..3
 * description: The function stores one character in display input buffer.
 */

L02_Return_Type Func_SetDisplay(DisplayPrompt character, int position)
{
    if((position >= 0) | (position <= 3))
    {
        DisplayInputBuffer[position] = character;
        return L02_E_OK;
    }
    else
    {
        return L02_E_NOT_OK;
    }
}



/*********************************************************************************************************************/
/*
 * function:    Func_Convert2Display
 * returns:     returns:     L02_Return_Type Error report
 * parameters:  void
 * description: The function converts the content of the input buffer to data as required by the display.
 */

L02_Return_Type Func_Convert2Display(void)
{
    L02_Return_Type tmp_L02;

    tmp_L02 = Func_EncodeDisplayInput(DisplayInputBuffer, DisplayInputEncoded);

    if (tmp_L02 == L02_E_OK)
    {
        tmp_L02 = Func_BuildDisplayOutput(DisplayInputEncoded, DisplayOutputBuffer);

        if (tmp_L02 == L02_E_OK)
        {
            tmp_L02 = Func_Build_ASCLIN_FIFO_Format(DisplayOutputBuffer, DisplayOutputFIFO);

            if (tmp_L02 == L02_E_OK)
            {
                return L02_E_OK;
            }
        }
    }
    return L02_E_NOT_OK;
}



