/**********************************************************************************************************************
 * \file IF_Display.h
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Harald Zweck.
 * If and as long as no such terms of use are agreed, use of this file is subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The definitions in this file structure the data format of the data to be displayed, according to the display
 * on the THD AdapterLite.
 */

/*
 * status: V01.0 2025-09-15
 */



/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/


#ifndef ADAPTERLITE_IF_DISPLAY_H_
#define ADAPTERLITE_IF_DISPLAY_H_

typedef enum _DisplayPrompt
{
    DispPrompt_0noDot = 0,
    DispPrompt_1noDot,
    DispPrompt_2noDot,
    DispPrompt_3noDot,
    DispPrompt_4noDot,
    DispPrompt_5noDot,
    DispPrompt_6noDot,
    DispPrompt_7noDot,
    DispPrompt_8noDot,
    DispPrompt_9noDot,
    DispPrompt_ONnoDot,
    DispPrompt_0withDot,
    DispPrompt_1withDot,
    DispPrompt_2withDot,
    DispPrompt_3withDot,
    DispPrompt_4withDot,
    DispPrompt_5withDot,
    DispPrompt_6withDot,
    DispPrompt_7withDot,
    DispPrompt_8withDot,
    DispPrompt_9withDot,
    DispPrompt_ONwithDot,
    DispPrompt_OFF,
    DispPrompt_Dot
} DisplayPrompt;


typedef struct _DisplayElementStruct
{
        uint8 ElementPositionCode;
        uint8 ElementShowCode;
} DisplayElementStruct;



#endif /* ADAPTERLITE_IF_DISPLAY_H_ */
