/**********************************************************************************************************************
 * \file ISR_GPT120_T6.c
 * \copyright Copyright (C) Harald Zweck 2025
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Harald
 *Zweck. If and as long as no such terms of use are agreed, use of this file is
 *subject to following:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------------Documentation----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * The code in this file shall provide the following functionalities:
 *
 *
 * The interrupt service routine (ISR), which is launched when timer GPT12 T6
 * expires.
 *
 * The ISR shall transfer the converted data to the ASCLIN Tx FIFO
 *
 */

/*
 * status: V01.0 2025-11-10
 */

/*********************************************************************************************************************/
/*-----------------------------------------------------Defines-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include <Level_02_Interfaces/TC375_IntVectorTable_CPU0/IntVectorTable_CPU0.h>
#include <Level_Libraries/Infra/Platform/Tricore/Compilers/Compilers.h>
#include <Level_Libraries/iLLD/TC37A/Tricore/Cpu/Std/Platform_Types.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxGpt12_reg.h>
#include "IfxSrc_reg.h"

#include <Level_02_Interfaces/Interface_Libraries/L02_Return_Types.h>
#include <Level_04_HAL/HAL_Libraries/HAL_Return_Types.h>

#include <Level_04_HAL/TC375_CAN/TC375_CAN_functions.h>
#include <Level_04_HAL/TC375_DMA/TC375_DMA_functions.h>
#include <Level_04_HAL/TC375_GPT12/TC375_GPT12_functions.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxDma_reg.h>
#include <Level_Libraries/Infra/Sfr/TC37A/_Reg/IfxPort_reg.h>

#include "FreeRTOS.h"
#include "task.h"

/*********************************************************************************************************************/
/*-----------------------------------------------------Externals-----------------------------------------------------*/
/*********************************************************************************************************************/

/*
 * References to external functions at Level HAL.
 */

extern HAL_Return_Type Func_transfer_to_TxFIFO(uint16 send_buffer[],
                                               uint16 amount_to_send);

extern uint16 DisplayOutputFIFO[4];
extern volatile uint16 CAN_TxCounterValue;
extern TaskHandle_t handle_task_Display;
extern L02_Return_Type Func_Adapter_LED1_on(void);
extern L02_Return_Type Func_Adapter_LED1_off(void);

/*********************************************************************************************************************/
/*-------------------------------------------------Global
 * variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function
 * Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*
 * function:    ISR_T6_expired
 * returns:     void
 * parameters:  void
 * description: The function is an ISR and is launched when the timer GPT120 T6
 * expires.
 */

extern volatile uint8 g_send_divider;
extern volatile uint8 g_send_tick;

IFX_INTERRUPT(ISR_T6_expired, 0, GPT12_T6_SRPN_CPU) {
  BaseType_t xHigherPriorityTaskWoken = pdFALSE;
  SRC_GPT120T6.B.CLRR = 0x1;
  SRC_GPT120T6.B.SWSCLR = 0x1;
  SRC_GPT120T6.B.IOVCLR = 0x1;

  if (g_send_divider != 0) {
    g_send_tick++;
    if (g_send_tick >= g_send_divider) {
      g_send_tick = 0;

      {
        uint16 value;
        Func_GPT12_T3_get_value(&value);
        value = (uint16)((value + 1u) & 0xFFFFu);
        Func_GPT12_T3_set_value(value);
      }

      /* DMA transfers T3 counter to CAN TX buffer DB0 (as per requirement) */
      /* Force DMA destination address before each transfer to prevent drift */
      MODULE_DMA.CH[1].DADR.U = 0xF0200408u;  /* Lock to correct address */
      MODULE_DMA.CH[1].SADR.U = (uint32)&MODULE_GPT120.T3.U;
      MODULE_DMA.CH[1].CHCSR.B.TCOUNT = 1u;
      DMA_TSR1.B.ECH = 1;                     /* Enable channel */
      MODULE_DMA.CH[1].CHCSR.B.SCH = 1;       /* Software trigger */

      /* Trigger CAN transmission */
      (void)Func_CAN_send_counter_via_dma();

      /* Notify Task_Display that a frame was sent */
      vTaskNotifyGiveFromISR(handle_task_Display, &xHigherPriorityTaskWoken);
    }
  }

  portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
}
